import type { Stay } from '@/types/Stay';

export const sampleStays: Stay[] = [
  {
    id: 'victoria-falls-hotel',
    name: 'The Victoria Falls Hotel',
    location: 'Victoria Falls',
    description:
      'Established in 1904, this iconic 5-star hotel offers breathtaking views of the Victoria Falls Bridge and the spray from the falls. Known as "the grand old lady of the Falls".',
    price: 320,
    perNight: true,
    rating: 4.8,
    imageUrl: 'https://picsum.photos/800/800?random=101',
    images: [
      'https://picsum.photos/800/800?random=101',
      'https://picsum.photos/800/800?random=102',
      'https://picsum.photos/800/800?random=103',
      'https://picsum.photos/800/800?random=104',
      'https://picsum.photos/800/800?random=105',
      'https://picsum.photos/800/800?random=106',
      'https://picsum.photos/800/800?random=107',
    ],
    amenities: ['Spa', 'Bar', 'Air Conditioning', 'WiFi', 'Pool', 'Restaurant', 'Gym'],
    host: {
      name: 'Victoria Falls Hotels',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
      joinedYear: '2019',
      responseRate: '98%',
      responseTime: 'Within an hour',
    },
    details: {
      guests: 4,
      bedrooms: 2,
      beds: 2,
      bathrooms: 2,
    },
  },
  {
    id: 'elephant-hills-resort',
    name: 'Elephant Hills Resort',
    location: 'Victoria Falls',
    description:
      'Set on a hill overlooking the Zambezi River, this resort offers an 18-hole championship golf course and views of the mist from Victoria Falls.',
    price: 195,
    perNight: true,
    rating: 4.3,
    imageUrl: 'https://picsum.photos/800/800?random=108',
    images: [
      'https://picsum.photos/800/800?random=108',
      'https://picsum.photos/800/800?random=109',
      'https://picsum.photos/800/800?random=110',
      'https://picsum.photos/800/800?random=111',
      'https://picsum.photos/800/800?random=112',
      'https://picsum.photos/800/800?random=113',
      'https://picsum.photos/800/800?random=114',
    ],
    amenities: ['WiFi', 'Pool', 'Restaurant', 'Golf Course', 'Bar', 'Conference Center'],
    host: {
      name: 'Elephant Hills Host Team',
      avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
      joinedYear: '2020',
      responseRate: '95%',
      responseTime: 'Within 2 hours',
    },
    details: {
      guests: 2,
      bedrooms: 1,
      beds: 1,
      bathrooms: 1,
    },
  },
  {
    id: 'the-kingdom-hotel',
    name: 'The Kingdom Hotel',
    location: 'Victoria Falls',
    description:
      'Designed to resemble the ancient Kingdom of Munhumutapa, this unique hotel features a man-made lake, waterfalls, and is within walking distance of Victoria Falls.',
    price: 150,
    perNight: true,
    rating: 4.1,
    imageUrl: 'https://picsum.photos/800/800?random=115',
    images: [
      'https://picsum.photos/800/800?random=115',
      'https://picsum.photos/800/800?random=116',
      'https://picsum.photos/800/800?random=117',
      'https://picsum.photos/800/800?random=118',
      'https://picsum.photos/800/800?random=119',
      'https://picsum.photos/800/800?random=120',
      'https://picsum.photos/800/800?random=121',
    ],
    amenities: ['WiFi', 'Pool', 'Restaurant', 'Casino', 'Bar', 'Air Conditioning'],
    host: {
      name: 'Kingdom Hospitality',
      avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150',
      joinedYear: '2018',
      responseRate: '92%',
      responseTime: 'Within 3 hours',
    },
    details: {
      guests: 3,
      bedrooms: 1,
      beds: 2,
      bathrooms: 1,
    },
  },
  {
    id: 'meikles-hotel',
    name: 'Meikles Hotel',
    location: 'Harare',
    description:
      'A five-star hotel in the heart of Harare with over 100 years of history, offering luxury accommodations with an outdoor pool and multiple dining options.',
    price: 240,
    perNight: true,
    rating: 4.6,
    imageUrl: 'https://picsum.photos/800/800?random=122',
    images: [
      'https://picsum.photos/800/800?random=122',
      'https://picsum.photos/800/800?random=123',
      'https://picsum.photos/800/800?random=124',
      'https://picsum.photos/800/800?random=125',
      'https://picsum.photos/800/800?random=126',
      'https://picsum.photos/800/800?random=127',
      'https://picsum.photos/800/800?random=128',
    ],
    amenities: ['Business Center', 'Gym', 'Spa', 'WiFi', 'Pool', 'Restaurant', 'Bar'],
    host: {
      name: 'Meikles Group',
      avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150',
      joinedYear: '2017',
      responseRate: '99%',
      responseTime: 'Within 30 minutes',
    },
    details: {
      guests: 2,
      bedrooms: 1,
      beds: 1,
      bathrooms: 1,
    },
  },
  {
    id: 'bronte-hotel',
    name: 'Bronte Hotel',
    location: 'Harare',
    description:
      'Set in lush gardens in central Harare, this boutique hotel offers tranquility with its beautiful grounds, outdoor pool, and cozy accommodations.',
    price: 175,
    perNight: true,
    rating: 4.4,
    imageUrl: 'https://picsum.photos/800/800?random=129',
    images: [
      'https://picsum.photos/800/800?random=129',
      'https://picsum.photos/800/800?random=130',
      'https://picsum.photos/800/800?random=131',
      'https://picsum.photos/800/800?random=132',
      'https://picsum.photos/800/800?random=133',
      'https://picsum.photos/800/800?random=134',
      'https://picsum.photos/800/800?random=135',
    ],
    amenities: ['WiFi', 'Pool', 'Restaurant', 'Gardens', 'Conference Facilities', 'Bar'],
    host: {
      name: 'Bronte Collection',
      avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150',
      joinedYear: '2021',
      responseRate: '94%',
      responseTime: 'Within 1 hour',
    },
    details: {
      guests: 2,
      bedrooms: 1,
      beds: 1,
      bathrooms: 1,
    },
  },
  {
    id: 'rainbow-towers',
    name: 'Rainbow Towers Hotel',
    location: 'Harare',
    description:
      'A landmark 5-star hotel in Harare featuring the iconic 19-story tower, offering luxury accommodation, fine dining, and extensive conference facilities.',
    price: 190,
    perNight: true,
    rating: 4.2,
    imageUrl: 'https://picsum.photos/800/800?random=136',
    images: [
      'https://picsum.photos/800/800?random=136',
      'https://picsum.photos/800/800?random=137',
      'https://picsum.photos/800/800?random=138',
      'https://picsum.photos/800/800?random=139',
      'https://picsum.photos/800/800?random=140',
      'https://picsum.photos/800/800?random=141',
      'https://picsum.photos/800/800?random=142',
    ],
    amenities: ['Casino', 'Conference Center', 'Gym', 'WiFi', 'Pool', 'Restaurant', 'Bar'],
    host: {
      name: 'Rainbow Hospitality',
      avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
      joinedYear: '2016',
      responseRate: '96%',
      responseTime: 'Within 2 hours',
    },
    details: {
      guests: 4,
      bedrooms: 2,
      beds: 2,
      bathrooms: 2,
    },
  },
  {
    id: 'ilala-lodge',
    name: 'Ilala Lodge',
    location: 'Victoria Falls',
    description:
      'The closest hotel to Victoria Falls, offering elegant accommodation with colonial-style décor. Hear the roar and see the spray of the Falls from the hotel.',
    price: 280,
    perNight: true,
    rating: 4.7,
    imageUrl: 'https://picsum.photos/800/800?random=143',
    images: [
      'https://picsum.photos/800/800?random=143',
      'https://picsum.photos/800/800?random=144',
      'https://picsum.photos/800/800?random=145',
      'https://picsum.photos/800/800?random=146',
      'https://picsum.photos/800/800?random=147',
      'https://picsum.photos/800/800?random=148',
      'https://picsum.photos/800/800?random=149',
    ],
    amenities: ['WiFi', 'Pool', 'Restaurant', 'Air Conditioning', 'Bar', 'Spa Services'],
    host: {
      name: 'Ilala Hotels',
      avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150',
      joinedYear: '2019',
      responseRate: '97%',
      responseTime: 'Within 1 hour',
    },
    details: {
      guests: 2,
      bedrooms: 1,
      beds: 1,
      bathrooms: 1,
    },
  },
  {
    id: 'amalinda-lodge',
    name: 'Amalinda Lodge',
    location: 'Matobo Hills',
    description:
      'A unique safari lodge built into the granite boulders of Matobo Hills. This eco-friendly lodge offers stunning views, rock art tours, and rhino tracking.',
    price: 410,
    perNight: true,
    rating: 4.9,
    imageUrl: 'https://picsum.photos/800/800?random=150',
    images: [
      'https://picsum.photos/800/800?random=150',
      'https://picsum.photos/800/800?random=151',
      'https://picsum.photos/800/800?random=152',
      'https://picsum.photos/800/800?random=153',
      'https://picsum.photos/800/800?random=154',
      'https://picsum.photos/800/800?random=155',
      'https://picsum.photos/800/800?random=156',
    ],
    amenities: ['WiFi', 'Pool', 'Restaurant', 'Safari Activities', 'Bar', 'Library'],
    host: {
      name: 'Amalinda Safaris',
      avatar: 'https://images.unsplash.com/photo-1521579971123-1192931a1452?w=150',
      joinedYear: '2015',
      responseRate: '91%',
      responseTime: 'Within 3 hours',
    },
    details: {
      guests: 3,
      bedrooms: 2,
      beds: 3,
      bathrooms: 2,
    },
  },
  {
    id: 'bumi-hills',
    name: 'Bumi Hills Safari Lodge',
    location: 'Lake Kariba',
    description:
      'Perched on a hill overlooking Lake Kariba, this luxury safari lodge offers breathtaking sunsets, wildlife viewing, and fishing experiences.',
    price: 550,
    perNight: true,
    rating: 4.8,
    imageUrl: 'https://picsum.photos/800/800?random=157',
    images: [
      'https://picsum.photos/800/800?random=157',
      'https://picsum.photos/800/800?random=158',
      'https://picsum.photos/800/800?random=159',
      'https://picsum.photos/800/800?random=160',
      'https://picsum.photos/800/800?random=161',
      'https://picsum.photos/800/800?random=162',
      'https://picsum.photos/800/800?random=163',
    ],
    amenities: ['Safari', 'Fishing', 'Horse Riding', 'WiFi', 'Pool', 'Restaurant', 'Spa', 'Bar'],
    host: {
      name: 'Bumi Hills Collection',
      avatar: 'https://images.unsplash.com/photo-1544723795-3fb6469f5b39?w=150',
      joinedYear: '2016',
      responseRate: '93%',
      responseTime: 'Within 4 hours',
    },
    details: {
      guests: 4,
      bedrooms: 2,
      beds: 3,
      bathrooms: 2,
    },
  },
  {
    id: 'troutbeck-resort',
    name: 'Troutbeck Resort',
    location: 'Nyanga',
    description:
      'A charming country inn located in the Eastern Highlands, featuring a trout-filled lake, 18-hole golf course, and beautiful mountain scenery.',
    price: 165,
    perNight: true,
    rating: 4.3,
    imageUrl: 'https://picsum.photos/800/800?random=164',
    images: [
      'https://picsum.photos/800/800?random=164',
      'https://picsum.photos/800/800?random=165',
      'https://picsum.photos/800/800?random=166',
      'https://picsum.photos/800/800?random=167',
      'https://picsum.photos/800/800?random=168',
      'https://picsum.photos/800/800?random=169',
      'https://picsum.photos/800/800?random=170',
    ],
    amenities: ['WiFi', 'Pool', 'Restaurant', 'Golf Course', 'Bar', 'Fishing', 'Horse Riding'],
    host: {
      name: 'Troutbeck Hospitality',
      avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150',
      joinedYear: '2014',
      responseRate: '90%',
      responseTime: 'Within 5 hours',
    },
    details: {
      guests: 4,
      bedrooms: 2,
      beds: 4,
      bathrooms: 2,
    },
  },
  {
    id: 'rainbow-hotel',
    name: 'Rainbow Hotel',
    location: 'Bulawayo',
    description:
      'A historic hotel in the heart of Bulawayo, offering comfortable accommodation with colonial charm and modern amenities.',
    price: 150,
    perNight: true,
    rating: 4.2,
    imageUrl: 'https://picsum.photos/800/800?random=171',
    images: [
      'https://picsum.photos/800/800?random=171',
      'https://picsum.photos/800/800?random=172',
      'https://picsum.photos/800/800?random=173',
      'https://picsum.photos/800/800?random=174',
      'https://picsum.photos/800/800?random=175',
      'https://picsum.photos/800/800?random=176',
      'https://picsum.photos/800/800?random=177',
    ],
    amenities: ['WiFi', 'Restaurant', 'Bar', 'Conference', 'Historic', 'City Center'],
    host: {
      name: 'Rainbow Bulawayo',
      avatar: 'https://images.unsplash.com/photo-1531891437562-4301cf35b7e4?w=150',
      joinedYear: '2013',
      responseRate: '88%',
      responseTime: 'Within 6 hours',
    },
    details: {
      guests: 2,
      bedrooms: 1,
      beds: 1,
      bathrooms: 1,
    },
  },
  {
    id: 'camp-hwange',
    name: 'Camp Hwange',
    location: 'Hwange',
    description:
      'An authentic safari camp located in the heart of Hwange National Park, offering incredible wildlife viewing opportunities and luxury tented accommodations.',
    price: 450,
    perNight: true,
    rating: 4.9,
    imageUrl: 'https://picsum.photos/800/800?random=178',
    images: [
      'https://picsum.photos/800/800?random=178',
      'https://picsum.photos/800/800?random=179',
      'https://picsum.photos/800/800?random=180',
      'https://picsum.photos/800/800?random=181',
      'https://picsum.photos/800/800?random=182',
      'https://picsum.photos/800/800?random=183',
      'https://picsum.photos/800/800?random=184',
    ],
    amenities: ['Safari', 'Wildlife Viewing', 'Bar', 'WiFi', 'Pool', 'Restaurant', 'Spa'],
    host: {
      name: 'Hwange Safari Team',
      avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150',
      joinedYear: '2012',
      responseRate: '94%',
      responseTime: 'Within 2 hours',
    },
    details: {
      guests: 4,
      bedrooms: 2,
      beds: 4,
      bathrooms: 2,
    },
  },
  {
    id: 'somalisa-camp',
    name: 'Somalisa Camp',
    location: 'Hwange',
    description:
      'A luxury tented camp offering an authentic African safari experience with exceptional game viewing and personalized service.',
    price: 520,
    perNight: true,
    rating: 4.8,
    imageUrl: 'https://picsum.photos/800/800?random=185',
    images: [
      'https://picsum.photos/800/800?random=185',
      'https://picsum.photos/800/800?random=186',
      'https://picsum.photos/800/800?random=187',
      'https://picsum.photos/800/800?random=188',
      'https://picsum.photos/800/800?random=189',
      'https://picsum.photos/800/800?random=190',
      'https://picsum.photos/800/800?random=191',
    ],
    amenities: ['WiFi', 'Pool', 'Restaurant', 'Air Conditioning', 'Bar', 'Spa Services'],
    host: {
      name: 'Somalisa Collection',
      avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150',
      joinedYear: '2015',
      responseRate: '92%',
      responseTime: 'Within 4 hours',
    },
    details: {
      guests: 3,
      bedrooms: 2,
      beds: 3,
      bathrooms: 2,
    },
  },
];

export function getStayById(id: string): Stay | undefined {
  return sampleStays.find(stay => stay.id === id);
}

export function getStaysByLocation(location?: string | null): Stay[] {
  if (!location || location.trim().length === 0 || location.toLowerCase() === 'all') {
    return sampleStays;
  }

  const normalizedLocation = location.toLowerCase();
  return sampleStays.filter(stay => stay.location.toLowerCase().includes(normalizedLocation));
}

export function cloneStay(stay: Stay): Stay {
  return {
    ...stay,
    images: [...stay.images],
    amenities: [...stay.amenities],
    host: stay.host ? { ...stay.host } : undefined,
    details: stay.details ? { ...stay.details } : undefined,
  };
}
