import type { ItineraryData } from '@/components';

// Mock itinerary data - this would normally come from an API
export const mockItineraryData: ItineraryData[] = [
  {
    id: '1',
    name: 'Emirates',
    message: 'Flight EK123 to Victoria Falls - Check-in opens 3 hours before',
    time: 'July 8, 2025 at 10:30 AM',
    actualTime: '10:30',
    endTime: '18:45',
    isRead: true,
    unreadCount: 0,
    avatar: 'EM',
    status: 'received',
    type: 'transport',
    date: '2025-07-08',
    location: 'OR Tambo (JNB)',
    duration: '8h 15m',
    price: 1250,
    currency: 'USD',
    confirmationCode: 'EK123ABC',
    notes: 'Window seat 23A confirmed',
  },
  {
    id: '2',
    name: 'Victoria Falls Hotel',
    message: 'Check-in: 2:00 PM - Presidential Suite with Falls View',
    time: 'July 8, 2025 at 2:00 PM',
    actualTime: '14:00',
    isRead: true,
    unreadCount: 0,
    avatar: 'VH',
    status: 'received',
    type: 'accommodation',
    date: '2025-07-08',
    location: 'Victoria Falls',
    duration: 'Check-in',
    price: 850,
    currency: 'USD',
    confirmationCode: 'VFH2025VIP',
    notes: 'Early check-in arranged, champagne welcome',
  },
  {
    id: '3',
    name: 'Flight of Angels',
    message: 'Helicopter tour over Victoria Falls - Premium package',
    time: 'July 9, 2025 at 9:00 AM',
    actualTime: '09:00',
    endTime: '09:30',
    isRead: false,
    unreadCount: 0,
    avatar: 'FA',
    status: 'received',
    type: 'activity',
    date: '2025-07-09',
    location: 'Victoria Falls Airport',
    duration: '30 minutes',
    price: 395,
    currency: 'USD',
    confirmationCode: 'FOA2025VIP',
    notes: 'Weight limit 120kg per person',
  },
  {
    id: '4',
    name: 'White Water Rafting',
    message: 'Full day Grade 5 rapids adventure on Zambezi River',
    time: 'July 9, 2025 at 7:00 AM',
    actualTime: '07:00',
    endTime: '17:00',
    isRead: false,
    unreadCount: 0,
    avatar: 'WR',
    status: 'received',
    type: 'activity',
    date: '2025-07-09',
    location: 'Zambezi River',
    duration: '10 hours',
    price: 145,
    currency: 'USD',
    confirmationCode: 'ZAM2025RAP',
    notes: 'Lunch and safety gear included',
  },
  {
    id: '5',
    name: 'The Boma Restaurant',
    message: 'Traditional African dinner with cultural show',
    time: 'July 9, 2025 at 7:30 PM',
    actualTime: '19:30',
    endTime: '22:00',
    isRead: true,
    unreadCount: 0,
    avatar: 'BR',
    status: 'received',
    type: 'dining',
    date: '2025-07-09',
    location: 'Victoria Falls',
    duration: '2.5 hours',
    price: 85,
    currency: 'USD',
    confirmationCode: 'BOMA2025',
    notes: 'Table for 4, dietary restrictions noted',
  },
  {
    id: '6',
    name: 'Hwange Safari Lodge',
    message: 'Full day game drive with professional guide',
    time: 'July 10, 2025 at 6:00 AM',
    actualTime: '06:00',
    endTime: '18:00',
    isRead: false,
    unreadCount: 0,
    avatar: 'HS',
    status: 'received',
    type: 'activity',
    date: '2025-07-10',
    location: 'Hwange National Park',
    duration: '12 hours',
    price: 220,
    currency: 'USD',
    confirmationCode: 'HWG2025SAF',
    notes: 'Lunch at watering hole, camera equipment provided',
  },
  {
    id: '7',
    name: 'Sunset Cruise',
    message: 'Zambezi River sunset cruise with dinner',
    time: 'July 11, 2025 at 4:30 PM',
    actualTime: '16:30',
    endTime: '19:00',
    isRead: true,
    unreadCount: 0,
    avatar: 'SC',
    status: 'received',
    type: 'activity',
    date: '2025-07-11',
    location: 'Zambezi River',
    duration: '2.5 hours',
    price: 75,
    currency: 'USD',
    confirmationCode: 'ZAM2025SUN',
    notes: 'Vegetarian options available',
  },
  {
    id: '8',
    name: 'Great Zimbabwe Tours',
    message: 'UNESCO World Heritage site tour with historian guide',
    time: 'July 15, 2025 at 8:00 AM',
    actualTime: '08:00',
    endTime: '16:00',
    isRead: false,
    unreadCount: 0,
    avatar: 'GZ',
    status: 'received',
    type: 'activity',
    date: '2025-07-15',
    location: 'Masvingo',
    duration: '8 hours',
    price: 165,
    currency: 'USD',
    confirmationCode: 'GZR2025HIS',
    notes: 'Hotel pickup included, comfortable walking shoes required',
  },
  {
    id: '9',
    name: 'Intercape Bus',
    message: 'Luxury coach to Harare Airport',
    time: 'July 16, 2025 at 2:00 PM',
    actualTime: '14:00',
    endTime: '19:30',
    isRead: true,
    unreadCount: 0,
    avatar: 'IB',
    status: 'received',
    type: 'transport',
    date: '2025-07-16',
    location: 'Victoria Falls to Harare',
    duration: '5.5 hours',
    price: 45,
    currency: 'USD',
    confirmationCode: 'IC2025VIP',
    notes: 'WiFi and refreshments included',
  },
  {
    id: '10',
    name: 'Victoria Falls Hotel',
    message: 'Check-out: 11:00 AM - Please settle any incidentals',
    time: 'July 12, 2025 at 11:00 AM',
    actualTime: '11:00',
    isRead: true,
    unreadCount: 0,
    avatar: 'VH',
    status: 'received',
    type: 'accommodation',
    date: '2025-07-12',
    location: 'Victoria Falls',
    duration: 'Check-out',
    price: 0,
    currency: 'USD',
    confirmationCode: 'VFH2025VIP',
    notes: 'Late check-out until 1 PM available on request',
  },
];

// Filter options
export const ITINERARY_FILTERS = [
  'All',
  'Today',
  'Past',
  'Stays',
  'Events',
  'ThingsToDo',
  'Flights',
  'Bus',
  'Dining',
] as const;

export type ItineraryFilter = (typeof ITINERARY_FILTERS)[number];

// Default filter
export const DEFAULT_FILTER: ItineraryFilter = 'All';

// View modes
export const VIEW_MODES = ['calendar', 'list'] as const;
export type ViewMode = (typeof VIEW_MODES)[number];
export const DEFAULT_VIEW_MODE: ViewMode = 'calendar';
